name: build_and_test

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.py'
      - '*.txt'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]

jobs:

  build_and_test:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:

    - uses: actions/checkout@main

    - name: Setup Golang
      uses: actions/setup-go@main
      with:
          go-version: '1.21.x'
          cache: true
          cache-dependency-path: "**/go.sum"
          
    - name: Setup Java
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Verify Java
      run: |
        java --version
        echo Java home is %JAVA_HOME%

    - name: Find DLLs
      if: runner.os == 'Windows'
      run: |
        DIR %JAVA_HOME%\bin\*.dll /s

    - name: Go Build
      run: |
        go get golang.org/x/sys
        go get github.com/ebitengine/purego
        go build -a -o . ./...

    - name: Try a Zip Test
      run: |
        ./essayer
